config/routes.rb
Rails.application.routes.draw do
  get 'index/index'

  resources :emails do
    resources :sections
  end

  resources :sections do
    resources :stories
  end

  root 'index#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  has_and_belongs_to_many :sections
  has_many :stories

  validates :name, presence: true,
                   length: { minimum: 5 }
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :stories
  has_and_belongs_to_many :sections

  validates :name, presence: true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :section
  belongs_to :email

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

  def index
    @emails = Email.all
  end

  def show
    @email = Email.find(params[:id])
  end

  def new
    @email = Email.new
  end

  def edit
    @email = Email.find(params[:id])
  end

  def create
    @email = Email.new(email_params)

    if @email.save
      redirect_to @email
    else
      render 'new'
    end
  end

  def update
    @email = Email.find(params[:id])

    if @email.update(email_params)
      redirect_to @email
    else
      render 'edit'
    end
  end

  def destroy
    @email = Email.find(params[:id])
    @email.destroy

    redirect_to emails_path
  end

  private
    def email_params
      params.require(:email).permit(:name)
    end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

    def index
      @sections = Section.all
    end

    def show
      @section = Section.find(params[:id])
    end

    def new
      @section = Section.new
    end

    def edit
      @section = Section.find(params[:id])
    end

    def create
      @section = Section.new(section_params)

      if @section.save
        redirect_to @section
      else
        render 'new'
      end
    end

    def update
      @section = Section.find(params[:id])

      if @section.update(section_params)
        redirect_to @section
      else
        render 'edit'
      end
    end

    def destroy
      @section = Section.find(params[:id])
      @section.destroy

      redirect_to sectioni_path
    end

    private
    def section_params
      params.require(:section).permit(:name, :tag)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def edit
    @story = Story.find(params[:id])
  end

  def create
    @section = Section.find(params[:section_id])
    @story = @section.stories.create(story_params)
    redirect_to section_path(@section)
  end

  def update
    @story = Story.find(params[:id])

    if @story.update(story_params)
      redirect_to @story
    else
      render 'edit'
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    redirect_to story_path
  end

  private
    def story_params
      params.require(:story).permit(:url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/index/index.html.erb
<h1>Welcome to Hubba Weekly</h1>

<%= link_to 'Click here to start', controller: 'emails' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HubbaWeekly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sections/index.html.erb
<table>
  <% @sections.each do |section| %>
    <tr>
      <td><%= section.name %></td>
      <td><%= link_to 'Show', section_path(section) %></td>
    </tr>
  <% end %>
</table>

app/views/sections/new.html.erb
<%= form_for([@section, @section.stories.build]) do |f| %>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/sections/show.html.erb
<h1><%= @section.name %></h1>

<h2>Story #1</h2>
<%= form_for([@section, @section.stories.build]) do |f| %>
  <p>
    <%= f.label :story_url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :story_description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<h2>Story #2</h2>
<%= form_for([@section, @section.stories.build]) do |f| %>
  <p>
    <%= f.label :story_url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :story_description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<h2>Story #3</h2>
<%= form_for([@section, @section.stories.build]) do |f| %>
  <p>
    <%= f.label :story_url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :story_description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', emails_path(@email) %>

app/views/stories/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/stories/_stories.html.erb
<p>
  <strong>Url:</strong>
  <%= story.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= story.description %>
</p>

app/views/stories/index.html.erb
<table>
  <% @stories.each do |story| %>
    <tr>
      <td><%= story.name %></td>
      <td><%= link_to 'Show', story_path(story) %></td>
      <td><%= link_to 'Edit', edit_story_path(story) %></td>
      <td><%= link_to 'Destroy', story_path(story),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete this Story?' }  %> </td>
    </tr>
  <% end %>
</table>

app/views/stories/new.html.erb
<h1>Story</h1>

<h2>Create a new Story</h2>

<%= render 'form' %>

<%= link_to 'Back', emails_path %>

app/views/stories/show.html.erb
<h1>Stories for <%= @section.title %></h1>

<h2>Stories</h2>
<%= render @section.stories %>

<h2>Add a story:</h2>
<%= form_for([@section, @section.stories.build]) do |f| %>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>